const ROUND_DAYS = 10;
const INCOME_TICK_MINUTES = 60;
const ATTACK_COOLDOWN_SECONDS = 30;
const ATTACK_ACTION_DURATION_SECONDS = 20;
const MAX_INFLUENCE = 100;
const MAP_SEED = "empire-city-v1";
const PHASE_DURATION_HOURS = 4;
const GAME_DAYS_PER_REAL_DAY = 3;
const GAME_CLOCK_START_HOUR = 6;

module.exports = {
  ROUND_DAYS,
  INCOME_TICK_MINUTES,
  ATTACK_COOLDOWN_SECONDS,
  ATTACK_ACTION_DURATION_SECONDS,
  MAX_INFLUENCE,
  MAP_SEED,
  PHASE_DURATION_HOURS,
  GAME_DAYS_PER_REAL_DAY,
  GAME_CLOCK_START_HOUR
};
